// AI bracket file format + parser.
//
// The admin can paste a JSON "picks file" describing a bracket (e.g. a
// prediction generated by an AI model) and drop it into one or more pools.
// To keep the file authorable by hand or from a model's prose, it uses a
// friendly "who reaches each round" shape rather than raw match IDs:
//
//   {
//     "nickname": "🤖 GPT-5",
//     "id": "gpt-5",                    // optional; defaults to slug(nickname)
//     "groups": {                       // predicted finishing order, 1st→4th
//       "A": ["MEX", "KOR", "RSA", "CZE"], ... all 12 groups A–L
//     },
//     "thirdPlaceAdvancers": ["A","C","D","F","H","I","K","L"],  // exactly 8
//     "advancers": {
//       "roundOf16":     [16 teams that win in the R32],
//       "quarterfinals": [8 teams that win in the R16],
//       "semifinals":    [4 teams that win in the QF],
//       "final":         [2 teams that win in the SF],
//       "champion":      "ARG",         // wins the Final
//       "thirdPlaceWinner": "FRA"       // wins the 3rd-place playoff
//     },
//     "finalGoalsGuess": 3              // optional tiebreaker
//   }
//
// Team tokens accept FIFA codes (MEX) or full names (Mexico), case-
// insensitively, plus a few common aliases. The parser resolves every
// match through resolveSlot/mapThirdPlaceAdvancers — exactly the logic the
// editor and scorer use — so a file that parses is guaranteed to be a
// complete, internally-consistent bracket the rest of the app will accept.

import { MATCHES, MATCHES_BY_ROUND } from '@/data/bracket';
import { GROUPS, GROUP_BY_LETTER, GROUP_LETTERS } from '@/data/groups';
import { TEAMS, TEAM_CODES } from '@/data/teams';
import { isComplete } from '@/lib/completeness';
import { resolveSlot } from '@/lib/resolveBracket';
import { mapThirdPlaceAdvancers } from '@/lib/thirdPlaceMap';
import type {
  BracketPicks,
  GroupLetter,
  GroupOrder,
  GroupPick,
  TeamCode,
} from '@/lib/types';

// Doc IDs for AI brackets are namespaced with this prefix. firestore.rules
// keys its admin-write carve-out off the same prefix, and real Google uids
// never contain a hyphen, so the namespace can't collide with a real user.
export const AI_ID_PREFIX = 'ai-';

export function aiBracketDocId(slug: string): string {
  return AI_ID_PREFIX + slug;
}

export function isAIBracketId(id: string): boolean {
  return id.startsWith(AI_ID_PREFIX);
}

export function slugify(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// --- team / group token normalization ------------------------------------

const CODE_SET = new Set(TEAM_CODES);
const NAME_TO_CODE = new Map<string, TeamCode>(
  TEAM_CODES.map((c) => [TEAMS[c].name.toLowerCase(), c]),
);

// Common ways a model or human might name a team that don't exactly match
// our code or our stored name. Lower-cased keys.
const TEAM_ALIASES: Record<string, TeamCode> = {
  'south korea': 'KOR',
  korea: 'KOR',
  'korea republic': 'KOR',
  usa: 'USA',
  us: 'USA',
  'united states of america': 'USA',
  turkey: 'TUR',
  turkiye: 'TUR',
  'ivory coast': 'CIV',
  "cote d'ivoire": 'CIV',
  "côte d'ivoire": 'CIV',
  'czech republic': 'CZE',
  bosnia: 'BIH',
  'bosnia and herzegovina': 'BIH',
  'cape verde': 'CPV',
  'dr congo': 'COD',
  'democratic republic of the congo': 'COD',
  'democratic republic of congo': 'COD',
  iran: 'IRN',
  'saudi arabia': 'KSA',
  'south africa': 'RSA',
  holland: 'NED',
};

export function normalizeTeam(token: unknown): TeamCode | null {
  if (typeof token !== 'string') return null;
  const t = token.trim();
  if (!t) return null;
  const up = t.toUpperCase();
  if (CODE_SET.has(up)) return up as TeamCode;
  const low = t.toLowerCase();
  return NAME_TO_CODE.get(low) ?? TEAM_ALIASES[low] ?? null;
}

function normalizeGroupLetter(token: unknown): GroupLetter | null {
  if (typeof token !== 'string') return null;
  const t = token.trim().replace(/^group\s+/i, '').toUpperCase();
  return (GROUP_LETTERS as string[]).includes(t) ? (t as GroupLetter) : null;
}

function teamName(code: TeamCode): string {
  return TEAMS[code]?.name ?? code;
}

// --- public types --------------------------------------------------------

export interface AIBracketFile {
  nickname: string;
  id?: string;
  groups: Record<string, TeamCode[]>;
  thirdPlaceAdvancers: GroupLetter[];
  advancers: {
    roundOf16: TeamCode[];
    quarterfinals: TeamCode[];
    semifinals: TeamCode[];
    final: TeamCode[];
    champion: TeamCode;
    thirdPlaceWinner: TeamCode;
  };
  finalGoalsGuess?: number | null;
}

export interface AIBracketSummary {
  champion: TeamCode;
  finalists: [TeamCode, TeamCode];
  thirdPlaceWinner: TeamCode;
}

export interface ParsedAIBracket {
  slug: string;
  docId: string;
  nickname: string;
  picks: BracketPicks;
  summary: AIBracketSummary;
}

export interface AIItemResult {
  index: number;
  label: string;
  ok: boolean;
  errors: string[];
  bracket?: ParsedAIBracket;
}

export interface AIParseResult {
  jsonError?: string;
  items: AIItemResult[];
}

// --- parsing -------------------------------------------------------------

export function parseAIBracketJson(text: string): AIParseResult {
  let data: unknown;
  try {
    data = JSON.parse(text);
  } catch (e) {
    return { jsonError: e instanceof Error ? e.message : String(e), items: [] };
  }
  const arr = Array.isArray(data) ? data : [data];
  const items = arr.map((raw, i) => parseOne(raw, i));

  // Reject duplicate doc IDs within a single paste — the second would
  // silently overwrite the first on write.
  const seen = new Map<string, number>();
  for (const it of items) {
    if (!it.ok || !it.bracket) continue;
    const prev = seen.get(it.bracket.docId);
    if (prev !== undefined) {
      it.ok = false;
      it.errors.push(
        `Duplicate id "${it.bracket.docId}" (also item ${prev + 1}). Give each bracket a unique nickname or "id".`,
      );
      it.bracket = undefined;
    } else {
      seen.set(it.bracket.docId, it.index);
    }
  }
  return { items };
}

function parseOne(raw: unknown, index: number): AIItemResult {
  const errors: string[] = [];
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    return { index, label: `item ${index + 1}`, ok: false, errors: ['Not a JSON object.'] };
  }
  const obj = raw as Record<string, unknown>;

  const nickname = typeof obj.nickname === 'string' ? obj.nickname.trim() : '';
  if (!nickname) errors.push('Missing "nickname".');
  const label = nickname || `item ${index + 1}`;

  const rawId = typeof obj.id === 'string' && obj.id.trim() ? obj.id : nickname;
  const slug = slugify(rawId);
  if (!slug) {
    errors.push('Could not derive an id from the nickname — add an "id" field with letters/numbers.');
  }

  const groups = parseGroups(obj.groups, errors);
  const advancingGroups = parseThirdPlace(obj.thirdPlaceAdvancers, errors);

  // Without valid groups + third-place we can't resolve any matchup, so
  // there's nothing more to check — surface what we have.
  if (!groups || !advancingGroups) {
    return { index, label, ok: false, errors };
  }

  const picks: BracketPicks = {
    groups,
    thirdPlace: { advancingGroups },
    knockout: {},
    finalizedAt: null,
    finalGoalsGuess: parseFinalGoals(obj.finalGoalsGuess, errors),
  };

  const summary = parseKnockout(obj.advancers, picks, errors);
  if (!summary || errors.length > 0) {
    return { index, label, ok: false, errors };
  }

  if (!isComplete(picks)) {
    errors.push('Bracket is incomplete after parsing — double-check the group orders and advancer lists.');
    return { index, label, ok: false, errors };
  }

  return {
    index,
    label,
    ok: true,
    errors,
    bracket: { slug, docId: aiBracketDocId(slug), nickname, picks, summary },
  };
}

function parseGroups(
  value: unknown,
  errors: string[],
): Record<GroupLetter, GroupPick> | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    errors.push('Missing or invalid "groups" object.');
    return null;
  }
  const byLetter = new Map<GroupLetter, unknown>();
  for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
    const letter = normalizeGroupLetter(k);
    if (letter) byLetter.set(letter, v);
  }

  const out = {} as Record<GroupLetter, GroupPick>;
  let ok = true;
  for (const letter of GROUP_LETTERS) {
    const v = byLetter.get(letter);
    if (!Array.isArray(v)) {
      errors.push(`Group ${letter}: missing finishing order (expected an array of 4 teams).`);
      ok = false;
      continue;
    }
    if (v.length !== 4) {
      errors.push(`Group ${letter}: expected exactly 4 teams, got ${v.length}.`);
      ok = false;
      continue;
    }
    const codes = v.map(normalizeTeam);
    const bad = codes
      .map((c, i) => (c ? null : String(v[i])))
      .filter((x): x is string => x !== null);
    if (bad.length) {
      errors.push(`Group ${letter}: unrecognized team(s): ${bad.join(', ')}.`);
      ok = false;
      continue;
    }
    const expected = GROUP_BY_LETTER[letter].teams;
    const got = new Set(codes as TeamCode[]);
    if (got.size !== 4 || !expected.every((c) => got.has(c))) {
      errors.push(
        `Group ${letter}: must be a reordering of exactly its 4 teams (${expected.join(', ')}).`,
      );
      ok = false;
      continue;
    }
    out[letter] = { order: codes as GroupOrder, committed: true };
  }
  return ok ? out : null;
}

function parseThirdPlace(value: unknown, errors: string[]): GroupLetter[] | null {
  if (!Array.isArray(value)) {
    errors.push('Missing "thirdPlaceAdvancers" (expected an array of 8 group letters).');
    return null;
  }
  const letters = value.map(normalizeGroupLetter);
  const bad = letters
    .map((l, i) => (l ? null : String(value[i])))
    .filter((x): x is string => x !== null);
  if (bad.length) {
    errors.push(`thirdPlaceAdvancers: unrecognized group(s): ${bad.join(', ')}.`);
    return null;
  }
  const set = new Set(letters as GroupLetter[]);
  if (set.size !== letters.length) {
    errors.push('thirdPlaceAdvancers: contains duplicate groups.');
    return null;
  }
  if (set.size !== 8) {
    errors.push(`thirdPlaceAdvancers: need exactly 8 groups, got ${set.size}.`);
    return null;
  }
  return [...set].sort() as GroupLetter[];
}

function parseFinalGoals(value: unknown, errors: string[]): number | null {
  if (value === undefined || value === null) return null;
  if (typeof value !== 'number' || !Number.isInteger(value) || value < 0 || value > 99) {
    errors.push('finalGoalsGuess: must be a whole number from 0 to 99 (or omitted).');
    return null;
  }
  return value;
}

function roundListName(round: string): string {
  return round === 'R32'
    ? 'roundOf16'
    : round === 'R16'
      ? 'quarterfinals'
      : round === 'QF'
        ? 'semifinals'
        : 'final';
}

function parseKnockout(
  value: unknown,
  picks: BracketPicks,
  errors: string[],
): AIBracketSummary | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    errors.push('Missing "advancers" object.');
    return null;
  }
  const a = value as Record<string, unknown>;
  const before = errors.length;
  const reachR16 = parseTeamList(a.roundOf16, 16, 'advancers.roundOf16', errors);
  const reachQF = parseTeamList(a.quarterfinals, 8, 'advancers.quarterfinals', errors);
  const reachSF = parseTeamList(a.semifinals, 4, 'advancers.semifinals', errors);
  const reachF = parseTeamList(a.final, 2, 'advancers.final', errors);
  const champion = parseSingleTeam(a.champion, 'advancers.champion', errors);
  const thirdWinner = parseSingleTeam(a.thirdPlaceWinner, 'advancers.thirdPlaceWinner', errors);
  // Structural problems make per-match resolution meaningless.
  if (errors.length > before || !reachR16 || !reachQF || !reachSF || !reachF || !champion || !thirdWinner) {
    return null;
  }

  if (!reachF.includes(champion)) {
    errors.push(`advancers.champion (${teamName(champion)}) must be one of advancers.final.`);
  }

  const setByRound: Record<string, Set<TeamCode>> = {
    R32: new Set(reachR16),
    R16: new Set(reachQF),
    QF: new Set(reachSF),
    SF: new Set(reachF),
  };
  const mapping = mapThirdPlaceAdvancers(picks.thirdPlace.advancingGroups);

  for (const m of MATCHES) {
    const home = resolveSlot(m.home, picks, mapping);
    const away = resolveSlot(m.away, picks, mapping);
    if (!home || !away) {
      errors.push(`Match ${m.id} (${m.round}): couldn't resolve both teams — check the earlier rounds.`);
      continue;
    }
    let winner: TeamCode | null = null;
    if (m.round === 'F') {
      if (champion === home || champion === away) winner = champion;
      else
        errors.push(
          `Final: champion ${teamName(champion)} isn't in the final (${teamName(home)} vs ${teamName(away)}).`,
        );
    } else if (m.round === '3rd') {
      if (thirdWinner === home || thirdWinner === away) winner = thirdWinner;
      else
        errors.push(
          `3rd-place playoff: ${teamName(thirdWinner)} isn't a semifinal loser (${teamName(home)} vs ${teamName(away)}).`,
        );
    } else {
      const set = setByRound[m.round];
      const homeIn = set.has(home);
      const awayIn = set.has(away);
      if (homeIn && !awayIn) winner = home;
      else if (awayIn && !homeIn) winner = away;
      else if (homeIn && awayIn)
        errors.push(
          `Match ${m.id} (${teamName(home)} vs ${teamName(away)}): both are listed in advancers.${roundListName(m.round)} — only one advances.`,
        );
      else
        errors.push(
          `Match ${m.id} (${teamName(home)} vs ${teamName(away)}): neither is listed in advancers.${roundListName(m.round)}.`,
        );
    }
    if (winner) picks.knockout[m.id] = { winner };
  }

  if (errors.length > before) return null;

  return {
    champion,
    finalists: MATCHES_BY_ROUND.SF.map((m) => picks.knockout[m.id]!.winner!) as [
      TeamCode,
      TeamCode,
    ],
    thirdPlaceWinner: thirdWinner,
  };
}

function parseTeamList(
  value: unknown,
  size: number,
  name: string,
  errors: string[],
): TeamCode[] | null {
  if (!Array.isArray(value)) {
    errors.push(`${name}: expected an array of ${size} teams.`);
    return null;
  }
  const codes = value.map(normalizeTeam);
  const bad = codes
    .map((c, i) => (c ? null : String(value[i])))
    .filter((x): x is string => x !== null);
  if (bad.length) {
    errors.push(`${name}: unrecognized team(s): ${bad.join(', ')}.`);
    return null;
  }
  const list = codes as TeamCode[];
  if (new Set(list).size !== list.length) {
    errors.push(`${name}: contains duplicate teams.`);
    return null;
  }
  if (list.length !== size) {
    errors.push(`${name}: expected ${size} teams, got ${list.length}.`);
    return null;
  }
  return list;
}

function parseSingleTeam(value: unknown, name: string, errors: string[]): TeamCode | null {
  const c = normalizeTeam(value);
  if (!c) {
    errors.push(`${name}: missing or unrecognized team.`);
    return null;
  }
  return c;
}

// --- inverse + template --------------------------------------------------

// Serialize a complete BracketPicks back into the file format. Used to
// generate the built-in template and for round-trip tests.
export function picksToAIFile(nickname: string, picks: BracketPicks): AIBracketFile {
  const groups: Record<string, TeamCode[]> = {};
  for (const letter of GROUP_LETTERS) {
    groups[letter] = [...picks.groups[letter].order] as TeamCode[];
  }
  const winnersOf = (round: string): TeamCode[] =>
    (MATCHES_BY_ROUND[round as keyof typeof MATCHES_BY_ROUND] ?? [])
      .map((m) => picks.knockout[m.id]?.winner)
      .filter((w): w is TeamCode => !!w);

  return {
    nickname,
    groups,
    thirdPlaceAdvancers: [...picks.thirdPlace.advancingGroups],
    advancers: {
      roundOf16: winnersOf('R32'),
      quarterfinals: winnersOf('R16'),
      semifinals: winnersOf('QF'),
      final: winnersOf('SF'),
      champion: picks.knockout[MATCHES_BY_ROUND.F[0].id]?.winner as TeamCode,
      thirdPlaceWinner: picks.knockout[MATCHES_BY_ROUND['3rd'][0].id]?.winner as TeamCode,
    },
    finalGoalsGuess: picks.finalGoalsGuess ?? null,
  };
}

// A complete, internally-consistent example: groups in their drawn order,
// the first 8 groups' third-place teams advancing, and the higher-listed
// (home) side winning every knockout. Built through the resolver so it's
// always valid — shown in the admin UI as a copyable starting point.
function buildExampleFile(): AIBracketFile {
  const groups = {} as Record<GroupLetter, GroupPick>;
  for (const g of GROUPS) {
    groups[g.letter] = { order: [...g.teams] as GroupOrder, committed: true };
  }
  const advancingGroups = GROUP_LETTERS.slice(0, 8);
  const picks: BracketPicks = {
    groups,
    thirdPlace: { advancingGroups },
    knockout: {},
    finalizedAt: null,
    finalGoalsGuess: 3,
  };
  const mapping = mapThirdPlaceAdvancers(advancingGroups);
  for (const m of MATCHES) {
    const home = resolveSlot(m.home, picks, mapping);
    const away = resolveSlot(m.away, picks, mapping);
    picks.knockout[m.id] = { winner: (home ?? away) as TeamCode };
  }
  return picksToAIFile('🤖 Example Bot', picks);
}

export const AI_BRACKET_TEMPLATE: AIBracketFile = buildExampleFile();
export const AI_BRACKET_TEMPLATE_JSON: string = JSON.stringify(AI_BRACKET_TEMPLATE, null, 2);
